services:
  backend:
    image: ghcr.io/atomicul/http-uploader/backend
    build: ./backend
    pull_policy: missing
    restart: on-failure:3
    environment:
      PORT: "3001"
      MAX_FILE_SIZE: "0"
      SAVE_DIRECTORY: /uploads
    ports:
      - "3001:3001"
    volumes:
      - "./uploads:/uploads"
  frontend:
    image: ghcr.io/atomicul/http-uploader/frontend
    build:
      context: ./frontend
      args:
        VITE_BACKEND_PORT: 3001
    pull_policy: missing
    restart: on-failure:3
    ports:
      - "3000:80"
